name: Latest Hashnode Posts

on:
  schedule:
    - cron: "0 0 * * 1" # Weekly instead of daily
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pull in Hashnode posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://api.rss2json.com/v1/api.json?rss_url=https://blog.thecodingant.in/rss.xml"
          custom_tags: "title/title,link/link,pubDate/pubDate"
